### PR TITLE
fix: docker volume permissions using gosu.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by cmoulliard** [comment]
I can't build the image locally
```
(1/2) Installing glibc (2.30-r0)
(2/2) Installing gosu (1.11-r1)
Executing busybox-1.30.1-r2.trigger
OK: 28 MiB in 26 packages
Removing intermediate container d1f4d24185da
 ---> 5858176f6aad
Step 4/12 : ADD https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.1/linux/oc.tar.gz ./
Downloading [==================================================>]  22.46MB/22.46MB
 ---> 99ace7307185
Step 5/12 : RUN tar -xzf oc.tar.gz &&     chmod +x oc &&     mv oc /usr/local/bin/ &&     rm -rf oc.tar.gz
 ---> Running in e0742793c10f
Removing intermediate container e0742793c10f
 ---> 917ae5e9df85
Step 6/12 : ARG username=hal
 ---> Running in 047824a07822
Removing intermediate container 047824a07822
 ---> f3efd351d70b
Step 7/12 : ARG userid=1000
 ---> Running in 006f09a675b1
Removing intermediate container 006f09a675b1
 ---> bf301512c744
Step 8/12 : ENV LOCAL_USER_NAME=$username
 ---> Running in 6ec31649695a
Removing intermediate container 6ec31649695a
 ---> 8964c5e63ac9
Step 9/12 : ENV LOCAL_USER_ID=$userid
 ---> Running in 9400564f2e83
Removing intermediate container 9400564f2e83
 ---> a0c215b853b1
Step 10/12 : ADD ./dist/hal_linux_amd64/hal /usr/local/bin/hal
ADD failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder453527212/dist/hal_linux_amd64/hal: no such file or directory
```

See error : @iocanel

**Comment by cmoulliard** [comment]
Forget my remark @iocanel as I was not building the linux binary of hal

**Comment by cmoulliard** [comment]
Problem persists using this image
```
docker run --rm --name hal -v "$(pwd)":/home/hal/lab -it  hal:pr39 bash
bash-5.0$ oc login https://195.201.87.126:8443 --token=TOKEN
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Logged into "https://195.201.87.126:8443" as "admin" using the token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    ap4k-intro
    aure
    auri-halkyon
    cert-manager
    claprun
    cmoullia
  * default
    demolab
    devtest
    gandrian
    generator
    gytis
    gytis-test
    halkyonio-site
    iocanel
    iocanel-rhte
    istio-operator
    istio-system
    kube-public
    kube-service-catalog
    kube-system
    kubedb
    logging
    management-infra
    nainaz
    openshift
    openshift-ansible-service-broker
    openshift-console
    openshift-infra
    openshift-logging
    openshift-monitoring
    openshift-node
    openshift-sdn
    openshift-template-service-broker
    openshift-web-console
    operators
    psp-example
    quarkus-test
    rhtelab
    snowdrop-site
    sso
    tekton-pipelines
    test

Using project "default".
Welcome! See 'oc help' to get started.
bash-5.0$ hal component spring-boot    -i fruit-backend-sb    -g me.fruitstand    -p me.fruitstand.demo    -s 2.1.6.RELEASE    -t crud    -v 1.0.0-SNAPSHOT    --supported=false    fruit-backend-sb
Selected Spring Boot: 2.1.6.RELEASE
Selected template: crud
Selected Group Id: me.fruitstand
Selected Artifact Id: fruit-backend-sb
Selected Version: 1.0.0-SNAPSHOT
Selected Package name: me.fruitstand.demo
FATA[0000] error running spring-boot: failed to download file /fruit-backend-sb.zip due to open /fruit-backend-sb.zip: permission denied
```
@iocanel

**Comment by iocanel** [comment]
Hmmm we need to cd ~

**Comment by iocanel** [comment]
@cmoulliard updated the PR

**Comment by cmoulliard** [comment]
Can you please test the image before to update it ?
```
docker run --rm --name hal -v "$(pwd)":/home/hal/lab -it hal:pr39 bash
error: exec: "cd": executable file not found in $PATH
```

**Comment by geoand** [comment]
Can someone give me the steps they would like me to test?

**Comment by iocanel** [comment]
@cmoulliard: updated and tested.

**Comment by cmoulliard** [comment]
> updated

The commit is still the same as before the error I reported @iocanel @geoand

**Comment by iocanel** [comment]
> > updated
> 
> The commit is still the same as before the error I reported @iocanel @geoand
Not sure why is that. Pushed again!

**Comment by geoand** [comment]
Cool fix!

**Comment by cmoulliard** [comment]
That works better now. Can you also add git/maven as tool as we don't package it within the image ? @iocanel @geoand 
Why : If we add git/maven, then the developers could play all the lab within the docker container

**Comment by geoand** [comment]
> That works better now. Can you also add git/maven as tool as we don't package it within the image ? @iocanel @geoand
> Why : If we add git/maven, then the developers could play all the lab within the docker container

Do we really want them to do that? Wouldn't that just cause more confusion the necessary (in the sense that if they have more options, more things could go wrong - in such a lab type scenario I believe the fewer the options the better).
I would assume everyone is expected to have `git` and `maven`

**Comment by cmoulliard** [comment]
If we don't embed git, maven within the image, then they will have to exit and execute several times `docker run` followed by oc login as kube config file is not persisted. Not really a great dev experience

**Comment by cmoulliard** [comment]
I will push nevertheless this image to quay now : `docker push quay.io/halkyonio/hal:v0.1.8`
We will see Monday what we could do to resolve the kube config file not persisted to avoid to have to install git/maven. Make sense @iocanel @geoand

**Comment by cmoulliard** [comment]
No need to add git or maven if we play the commands as showed here: Find a workaround --> https://github.com/halkyonio/rhte_lab_2019/issues/18#issuecomment-533669202

I will merge the PR

**Pull request merged**
